### ISSUE TITLE
Default town tune is off-key

### ISSUE THREAD

**Issue by PikaDude** [animal-crossing-music-extension/ac-music-extension#103]
Current default town tune:
![image](https://user-images.githubusercontent.com/18642415/75106544-e7e41880-5671-11ea-81e9-55d47ebe676b.png)
Actual default town tune: 
![image](https://user-images.githubusercontent.com/18642415/75106535-da2e9300-5671-11ea-9c5b-5716eecf61ad.png)
What it should really look like: 
![image](https://user-images.githubusercontent.com/18642415/75106547-ef0b2680-5671-11ea-80e9-46f3851cffe0.png)

**Comment by Julian-MM** [comment]
If you try playing that tune, does it sound inaccurate to the in-game pitches? I found those higher pitches to do so, it may be a problem of the availablePitches being inaccurate to the games' pitches

**Comment by PikaDude** [comment]
If I copy the tune note for note, it sounds exactly the same as the in-game one. The current default one sounds off-key.

**Comment by Julian-MM** [comment]
Changed the default in branch fix/town-tune-E3

The new default town tune can be merged with /develop/ once the E3 note is fixed
