### ISSUE TITLE
Creating an iPhone/android app for this extension.

### ISSUE THREAD

**Issue by Andy608** [animal-crossing-music-extension/ac-music-extension#108]
Hi,

So I've been using this app for a few years and I'm really excited to see it being worked on again. I would love to make an iPhone/Android app that does the same thing as the chrome extension. It would advertise this plugin and pretty much serve a way for users on mobile to use this plugin since chrome apps aren't available to them.

If this mobile project is something you don't want affiliated with this extension, I understand. Please let me know your thoughts one way or another!

Thanks,
Andrew

**Comment by PikaDude** [comment]
In my personal opinion, I'd prefer just to keep things the way that they are as trying to keep both in sync with updates would be a challenge, and stuff like that would also fall out of the project's scope. A workaround that does allow users to install the extension onto their Android phones is via an app called Kiwi Browser which allows users to install chrome extensions as they would on desktop. Additionally, a lite version of the extension that runs as a standalone website could potentially happen in the future. The main concern of publishing an app for iOS is Apple being stricter with the use of the music, Google is quite laid back with allowing apps on their stores in comparison. It's up to the others if they want anything else to happen too, this is just my personal opinion as this has been brought up by many others before.

**Comment by Andy608** [comment]
That's understandable. That's why I figured I'd ask first. Thanks for letting me know!
