### ISSUE TITLE
Error with Town Tune Player

### ISSUE THREAD

**Issue by lilspooni** [animal-crossing-music-extension/ac-music-extension#112]
Hello! When the hour comes to a close and the town tune begins to play, anytime the high E is to be played the audio goes silent. I don't know what is causing this. It plays fine when I ask it to, so I can hear the tune I've made, it is only when the time comes for the tune to be officially chimed that it skips all High E notes.

**Comment by lilspooni** [comment]
Hello! When the hour comes to a close and the town tune begins to play, anytime the high E is to be played the audio goes silent. I don't know what is causing this. It plays fine when I ask it to, so I can hear the tune I've made, it is only when the time comes for the tune to be officially chimed that it skips all High E notes. I did not mean to close the first one of these i made.

**Comment by PikaDude** [comment]
Duplicate of #102

**Comment by lilspooni** [comment]
No, I made a mistake and closed the first one without meaning to. I just want to listen to my town tune chime correctly. This is still an issue

**Comment by PikaDude** [comment]
This issue has already been fixed in the develop branch, which is pending for a release. You can follow the instructions in the [README to install the development version](../#source-code-development-version) which has the fix, but I recommend you just wait for the proper release.
