### ISSUE TITLE
Issue with the Town Tune Hourly Chime

### ISSUE THREAD

**Issue by lilspooni** [animal-crossing-music-extension/ac-music-extension#113]
Hello! When the hour comes to a close and the town tune begins to play, anytime the high E is to be played the audio goes silent. I don't know what is causing this. It plays fine when I ask it to, so I can hear the tune I've made, it is only when the time comes for the tune to be officially chimed that it skips all High E notes.

**Comment by PikaDude** [comment]
Duplicate of #102. Next time re-open your previous issue instead of creating another one.
