### ISSUE TITLE
The Town tune is played to slowly

### ISSUE THREAD

**Issue by kiryHayashi** [animal-crossing-music-extension/ac-music-extension#117]
Hi!
When it's o'clock the Town tune sounds very slowly, and when I play it in the editor it sounds good, it's possible to fix it? 

Thank you beforehand.

**Comment by Julian-MM** [comment]
Hi!
This is intentional, the BPM of the town tune as it's played at the hour is lower than when it's played when you edit it, because that's how it's done in the games. Unless we add a feature to choose which version you play at the hour, which is unlikely, this is won't be changed.
