### ISSUE TITLE
Possibility to cast through Chrome

### ISSUE THREAD

**Issue by FrancisFire** [animal-crossing-music-extension/ac-music-extension#120]
The only thing I think is missing is the possibily to cast the audio from the extension to any compatible device (such as Google Home/Google Nest and Chromecast) through the Chrome Browser

**Comment by PikaDude** [comment]
Due to the limitations of Chrome extensions, I don't believe this is possible. The only way to perhaps get this to work is to cast your entire desktop with the extension playing, sorry.
