### ISSUE TITLE
Animal Crossing: New Horizons

### ISSUE THREAD

**Issue by elesafan85** [animal-crossing-music-extension/ac-music-extension#121]
Will you be adding the hourly music from AC:NH as an option once the game releases?

**Comment by paladique** [comment]
Hey @elesafan85! We'd LOVE to do that, but unsure if our timeline will match with the release. We'll keep your issue open so you'll know when that happens.

**Comment by elesafan85** [comment]
Thanks! I'm super hyped for the new release, and love using this extension!
wish you all the best!
