### ISSUE TITLE
Singapore Postal Code not accepted

### ISSUE THREAD

**Issue by sonicEX238** [animal-crossing-music-extension/ac-music-extension#126]
Putting in a 6 digit postal code doesn't work. Tried it everywhere in singapore. 

Only accepted with a 5-Digit Postal Code in MY which is the closest. but weather doesn't work like that! 

Hope you can fix it! love the extension!

**Comment by PikaDude** [comment]
Hi, we're aware of issues with the current live weather system, and we are planning on allowing users to enter their location specifically rather than using the unreliable postal code system. This issue is located here #79. For now there is no solution, sorry.
