### ISSUE TITLE
Music won't play

### ISSUE THREAD

**Issue by ferny-boi** [animal-crossing-music-extension/ac-music-extension#127]
Hey!! Sorry if this has already been solved, but it's been bugging me all day long. No matter what I do, the extension just will not play the music. I've been in the options about a hundred times, I've removed and re-added the extension, and I've even restarted my computer. I made sure there's no other audio playing from anywhere on my computer, and I even put the setting on to not stop the music if it were, and no luck. I've clicked the extension on and off, but it goes to the time for a split second and then a little red box with an "x" appears at the bottom right corner of the leaf. It's weird to me because I've had the extension for a while, I just haven't had it activated. Hope there's a fix!!! Thank you for your time :^)

**Comment by PikaDude** [comment]
Hi! Can you try accessing https://acmusicext.com and reporting the results?

**Comment by ferny-boi** [comment]
I don't know what that did, but the music is playing now!!! I opened up the link and nothing really happened, so I took a minute to have lunch before I responded, and right at the hour my town theme played and the music started !!!! Thank you so much !!!!!!!!!

**Comment by PikaDude** [comment]
No problem haha, I'm glad you got it working.
