### ISSUE TITLE
Unknown Error Trying to update zip location

### ISSUE THREAD

**Issue by e-riveras** [animal-crossing-music-extension/ac-music-extension#136]
So I tried updating my location to Santiago, CL (code: 8320000, cl) and it shows that an unknown error ocurred.

Platform: Chrome Version 81.0.4044.138 (Official Build) (64-bit)
Version: 4.2.0

**Comment by paladique** [comment]
@waio1990 thanks for reporting this issue! We are already tracking this in #79 so we'll close this to prevent duplicates.
