### ISSUE TITLE
Live Weather Location

### ISSUE THREAD

**Issue by FalconPunnnch** [animal-crossing-music-extension/ac-music-extension#138]
Hey! I tried to enter my zip code(15036) and ISO code (PER/PE) to the live weather but it doesn't work  :(  It says that "An unknown error occurred" :'((

Please, can u fix this? I would like to listen at rainy music like the weather in here u.u

Thank you!!

**Comment by paladique** [comment]
@GineDBZ thanks for reporting this issue! We are already tracking this in #79 so we'll close this to prevent duplicates.
