### ISSUE TITLE
missing from Chrome Web Extensions Store

### ISSUE THREAD

**Issue by starcestus** [animal-crossing-music-extension/ac-music-extension#145]
Is there a reason the extension is missing from the web store? A friend of mine wanted this but cant install it directly anymore

**Comment by PikaDude** [comment]
We're aware of this issue, and are working on trying to figure out what's happened.

**Comment by JoeDuncko** [comment]
FYI you should probably update the readme and website to reflect the issue. And probably leave this issue unresolved until the extension is back on the store. I thought I was doing something wrong!

**Comment by Kippykip** [comment]
Did it get a copyright takedown or something?
