### ISSUE TITLE
Removed chrome extension page

### ISSUE THREAD

**Issue by 4geru** [animal-crossing-music-extension/ac-music-extension#151]
chrome web store page is not found, so i cannot import this extenstion :(
https://chrome.google.com/webstore/detail/animal-crossing-music/fcedlaimpcfgpnfdgjbmmfibkklpioop

**Comment by AngelOfMelody** [comment]
You have to download/install it directly from github, google took it down, cf discord / twitter

**Comment by Julian-MM** [comment]
Here's a guide: https://github.com/animal-crossing-music-extension/ac-music-extension#installation
