### ISSUE TITLE
It doesn't appears in the Chrome Web Store

### ISSUE THREAD

**Issue by Hirokonara** [animal-crossing-music-extension/ac-music-extension#155]
I was searching  "animal crossing music" in the chrome web store and it appears the error 404 pls fix that :(

**Comment by ilikecorndogs** [comment]
It has been that way for a year, we can't do anything about it unless google got back to the dev team when they reached out. The only thing you can do is download it and use it from GitHub. Please keep bug reports to bugs so they can be productive.

**Comment by unluckylylac** [comment]
yes but how do you use it? im new to github and its kinda hard to navigate haha

**Comment by nyakase** [comment]
Read the tutorial here (source code section): https://github.com/animal-crossing-music-extension/ac-music-extension#installation

For reference, the ZIP is at https://github.com/animal-crossing-music-extension/ac-music-extension/archive/refs/heads/develop.zip.

**Comment by Julian-MM** [comment]
Thanks for assisting @Vukkyy (And for linking the zip directly too that's helpful)
Google isn't very responsive, so its unsure when or if this extension can get back up, we might find some alternative but for now the only option is what Vukkyy replied
