### ISSUE TITLE
Extension not available anymore on the Chrome Web Store

### ISSUE THREAD

**Issue by DrJume** [animal-crossing-music-extension/ac-music-extension#156]
Sadly, the url to the Chrome Web Store leads to an error 404.
It seems to be not available for some time now.

What is the reason for this? Could you reupload the extension?

**Comment by dannyhpy** [comment]
The extension has been removed from Chrome Web Store. To use it on Chrome, download the **compressed archive** [like so](https://i.imgur.com/4uF9uJc.png).

Then, uncompress that archive somewhere on your PC.

Then go to **chrome://extensions** on your Chrome browser.
- Enable **Developer mode**
- Click **Load unpacked**
- Select the folder where the extension resides

---
EDIT: Someone made a _detailled guide_ at https://imgur.com/a/LaElgl3
