### ISSUE TITLE
On/off toggle via keyboard shortcut

### ISSUE THREAD

**Issue by TheIronMarx** [animal-crossing-music-extension/ac-music-extension#20]
A little icon in the side doesn't work well with my flow. It would be great to have keyboard shortcut which would turn on and off, or better yet pause, the music.

**Comment by TheDirtySpaceman** [comment]
Hi there @TheIronMarx, this is actually a global feature controlled by chrome. If you click on the three bars in chrome then go to settings, then to the extensions section, scroll all the way to the bottom then click the link that says 'Keyboard Shortcuts' you can assign a keystroke to turn the player on and off.

**Comment by paladique** [comment]
This looks like this was resolved, please reopen if not.
