### ISSUE TITLE
Options menu does not work

### ISSUE THREAD

**Issue by ghost** [animal-crossing-music-extension/ac-music-extension#21]
When I try to open up the options menu, a blank screen pops up: 
![image](https://cloud.githubusercontent.com/assets/14141561/15269647/aa7dfd4e-19fd-11e6-854d-2fb0cdbc1657.png)

I am on Google Chrome Stable Version 50.0.2661.102 m (64-bit).

Thank you for putting in your time and effort into developing and releasing this extension.

EDIT: I have found a workaround for accesing the options menu.

https://gfycat.com/GiddyHelplessFlamingo

By manually typing in the extension's address, followed by options.html, I am able to access it.
.

**Comment by paladique** [comment]
A new version of the extension is currently under development, and I cannot repro this issue. Closing for now.
