### ISSUE TITLE
Music copyright 

### ISSUE THREAD

**Issue by mainrs** [animal-crossing-music-extension/ac-music-extension#27]
Out of curiosity, under which license it the music from animal crossing? I hear it often in youtube videos and streams used as background music.
Just curious.

**Comment by JdotCarver** [comment]
It's fair use. The project is not intended to bring any kind of revenue or publicity. A fan creation for the fans. But I'm sure if it were actually popular Nintendo (as we all know their uncompromising ways) wouldn't see it that way. So it's a boon it's a niche appeal. :)

**Comment by mainrs** [comment]
Thanks!
