### ISSUE TITLE
Is this still being worked on?

### ISSUE THREAD

**Issue by KonradStuewe** [animal-crossing-music-extension/ac-music-extension#28]
The github version is v3.4 but the one in the web store is still v3. So will the extension eventually be updated or has development completely stopped on this project?

(I know this isn't the right place for questions like this. It's just that I don't know where to ask this instead)

**Comment by JdotCarver** [comment]
Development has stopped unfortunately. But anybody willing to pick it up is free to do so as they please as long as they credit the people that worked on it.

**Comment by AnimeGeek01** [comment]
I would add Wild world and let's go to the city rainy and snow version but i suck at coding

**Comment by paladique** [comment]
This is currently under development in this [forked repo](https://github.com/PikaDude/ac-music-extension-revived).
