### ISSUE TITLE
Make the Town Melody play anytime

### ISSUE THREAD

**Issue by Kyusetzu** [animal-crossing-music-extension/ac-music-extension#32]
I would love to hear my town melody even when I don't listen to the soundtrack.
Maybe you can make this a selectable thing.

**Comment by JdotCarver** [comment]
Hey there,
So you'd want no music, but only the town melody on hour change?

Saturday, 25 May 2019, 02:02PM +02:00 from Kyusetzu notifications@github.com<mailto:notifications@github.com>:


I would love to hear my town melody even when I don't listen to the soundtrack.
Maybe you can make this a selectable thing.

**Comment by Kyusetzu** [comment]
Yeah, that would an awesome option.
Having like an button for "Just play the town melody every hour" that could be toggled.
