### ISSUE TITLE
notifications

### ISSUE THREAD

**Issue by markimoofan** [animal-crossing-music-extension/ac-music-extension#34]
notifications don't work

**Comment by PikaDude** [comment]
Have notifications been enabled under the extension options?
![chrome_2020-01-14_11-21-53](https://user-images.githubusercontent.com/18642415/72303060-1d373700-36c0-11ea-8574-4fdb0cee3af9.png)

**Comment by PikaDude** [comment]
Just gonna close this as there isn't enough information provided. This issue's pretty old and because of that I doubt we'll get anything new from it. Feel free to reopen this if more information comes to light.
