### ISSUE TITLE
Enable the user to either choose Live K.K. songs or Aircheck songs

### ISSUE THREAD

**Issue by JdotCarver** [animal-crossing-music-extension/ac-music-extension#4]
I've tried to fiddle around with the files to realize that the best way I can see to do this would be by:  
- adding a checkbox underneath the 3 K.K. options saying "Play K.K. Aircheck songs instead"  
- which would replace the value of **currentMusic** to **kkac** in:

``` javascript
// get path of a song file
    function setAudioUrl(file) {
        if (checkKK()) {
            currentMusic = 'kk';
        }
        else {
            currentMusic = options.music;
            file += 'm';
        }
        audio.src = '../' + currentMusic + '/' + file + '.ogg';
```

The **kkac** music is in the Resources category on the readme

**Comment by PikaDude** [comment]
Closed in d2dd047d367a235f4232057b7af1d94c4b94cecb
