### ISSUE TITLE
the extension is still functional when I close chrome.

### ISSUE THREAD

**Issue by elesafan85** [animal-crossing-music-extension/ac-music-extension#41]
when I exit google chrome, the extension somehow still plays, even though it should only be functional inside the browser. this may be a problem on my end, but I felt I should inform you anyway.

**Comment by JdotCarver** [comment]
Hey there elesafan85,
Have you checked this? 
![chrome_KHtaAps9wO](https://user-images.githubusercontent.com/7091684/68095366-1f536d00-fea9-11e9-9bfb-2777b1eca0c6.png)

**Comment by elesafan85** [comment]
I turned it off and that did the trick, thanks! I don't know how it got
turned on in the 1st place, though. I had to search for the setting just to
find it so maybe I turned it on by accident one time.
