### ISSUE TITLE
Setting up a town melody

### ISSUE THREAD

**Issue by IsabelleTheDog** [animal-crossing-music-extension/ac-music-extension#42]
i am having trouble setting up a town melody, how do i set one up?

**Comment by syntholly** [comment]
Hi @IsabelleTheDog, are you using the Chrome Web Store version at the moment?

If so, that's currently out of date and doesn't come with that functionality just yet. We'll be releasing a fresh version soon. If you can just confirm that's the version you're using, I can reply here when we do update it.

**Comment by viridiancity** [comment]
@vSanjo Does the town melody not work ? Mine does.

**Comment by PikaDude** [comment]
This issue has become stale and not enough information has been provided. If any new information comes to light, feel free to reopen this issue.
