### ISSUE TITLE
I just want to point out

### ISSUE THREAD

**Issue by AnimeGeek01** [animal-crossing-music-extension/ac-music-extension#45]
wild world and Let's go the City are missing both their snow and rain versions. I've got the tunes on my flash drive if you need them.

**Comment by JdotCarver** [comment]
Hey AnimeGedk01, 
Thanks for the offer but it's on the coding part that we could do with some help. So unless you can find someone to help in that way too these files won't be much use. But still thanks!

**Comment by syntholly** [comment]
Hi @AnimeGeek01 - this is being worked on very soon!

We appreciate your offer, but we wouldn't want you getting in trouble distributing those files.

**Comment by PikaDude** [comment]
Song have been added in PikaDude/ac-music-extension-revived#1
