### ISSUE TITLE
Dynamic Music according to local Weather

### ISSUE THREAD

**Issue by JdotCarver** [animal-crossing-music-extension/ac-music-extension#5]
I have just received a mail from a user that wanted to help out. Hopefully we will be able to use this to implement the feature. Here is what he had to say:

**"** 
_It should be simple enough to use the OpenWeatherMap API (http://openweathermap.org/current) to periodically get the local weather for a city of the user's choice and determine whether to play sunny/rainy/snowy music. Granted the user can do it manually, but I think this would be a cute feature if it doesn't take much time to implement._

_tl;dr of above link --_

```
call http://api.openweathermap.org/data/2.5/weather?q=CityName&mode=xml 
and check precipitation.mode: "no" = sunny, "rain" = rainy, "snow" = snowy.
```

**"**

and then you'd need to make it change the value of option.music in:

``` javascript
// get path of a song file
function setAudioUrl(file) {
    if (checkKK()) {
        currentMusic = 'kk';
    }
    else {
        currentMusic = options.music;
        file += 'm';
    }
    audio.src = '../' + currentMusic + '/' + file + '.ogg';
}
```

to switch weather music type and BAM.

**Comment by ghost** [comment]
Any luck figuring this out since this post?

**Comment by GammaGames** [comment]
I did some work here: 4af9cd9, it seems to be working but it still needs more testing
I'm still new to git so I'm unsure how to reference issues when I commit

edit: It fetches the weather fine but isn't storing it for use getting the current music. Gotta work on it a little more

edit2: I used a timeout to force a music restart after the weather was fetched and it appears to be working. I'll might fork [kylechu's](https://github.com/kylechu/Animal-Crossing-Music-Extension) and add the features, his OOP format will be much nicer to work with in the future

edit3: Have succesfully updated to the OOP format

**Comment by JdotCarver** [comment]
And his format is now merged. :)

**Comment by navarr** [comment]
I see this has been merged - has it been released?  I can't find the option

**Comment by JdotCarver** [comment]
Yeah unfortunately I lack the knowledge and we lack the manpower to merge all commits and ensure proper support of the extension. So I'd rather have it all on git hub where savvier people can do what they please with it and let the stable version sit on the Chrome Store. :)
