### ISSUE TITLE
No longer playing in Opera for me getting error.

### ISSUE THREAD

**Issue by Thievsly** [animal-crossing-music-extension/ac-music-extension#58]
I get this error when trying to play in Opera Version:66.0.3515.72

Info

Uncaught TypeError: Cannot read property 'setActionHandler' of undefined

Context  

_generated_background_page.html

// Make notifyListeners public to allow for easier notification sending.
	window.notify = notifyListeners;

	if (DEBUG_FLAG) {
		window.setTime = function (hour, playTownTune) {
			notifyListeners("hourMusic", [hour, options.weather, options.music, playTownTune]);
		};
	}

}

**Comment by PikaDude** [comment]
Hi! We're aware of the extension not working in Opera and other Chromium-based browsers. It is because the extension has support for a Chrome-only feature known as "MediaSession". We are working on a fix.

**Comment by Kippykip** [comment]
Yeah noticed this too
