### ISSUE TITLE
Alternate icon(s) in browser

### ISSUE THREAD

**Issue by Hyarwen** [animal-crossing-music-extension/ac-music-extension#6]
As per readme. Adding this as an issue as I'm currently working on it.

**Comment by JdotCarver** [comment]
The guy simply suggested the AC leaf as an alternative. I think having it in its original color and B&W would be enough but feel free to add anything you deem necessary too.

**Comment by jordigarcl** [comment]
I believe this issue should be closed, as it has become stale.
