### ISSUE TITLE
Rework live weather inputs

### ISSUE THREAD

**Issue by PikaDude** [animal-crossing-music-extension/ac-music-extension#60]
At the moment, the text accompanying the live weather inputs in options are quite misleading, saying it needs a country code to function when it's actually looking for an ISO code. And also, the link from the zip codes text leads to a pretty shoddy website, a better one would be https://worldpostalcode.com/

**Comment by jordigarcl** [comment]
Linking this to #71 

The current zipcode link (http://www.geonames.org/postal-codes/) is not that bad, but the one you suggest is better. I agree to update it, will do so 👍
