### ISSUE TITLE
Tab Audio Behavior is inconsistent in Opera

### ISSUE THREAD

**Issue by ilikecorndogs** [animal-crossing-music-extension/ac-music-extension#63]
Most of the time, the Tab Audio Behavior does not react when audio starts or stops playing in a tab. instead reacting when the settings tab is selected. Sometimes it may react as intended, however it is uncommon.

**Comment by PikaDude** [comment]
This is simply because Opera doesn't send the "onUpdated" event for tabs when a tab's audible state is updated. Working on a fix now. Thanks Opera.
