### ISSUE TITLE
Allow volume of town tune to be edited

### ISSUE THREAD

**Issue by PikaDude** [animal-crossing-music-extension/ac-music-extension#66]
Right now, the town tune player ignores the volume of the music and there is no way to even change the volume. It currently plays at 100% volume and can be quite annoying.

**Comment by Julian-MM** [comment]
Would changing the gainLevel variable at line 12 of /scripts/global/tune_player.js do the trick?

**Comment by PikaDude** [comment]
Perhaps, but maybe we should maybe include a separate slider to control the town tune volume separately from the music volume, in case people find one or the other too loud for their liking. What do you think?

**Comment by Julian-MM** [comment]
Definitely, a separate volume slider on the Town Tune page would be easy to implement, and some people may, as you say, want the Town Tune to be quieter.
