### ISSUE TITLE
Zip codes and country codes do not work for latin american cities 

### ISSUE THREAD

**Issue by fortunachan** [animal-crossing-music-extension/ac-music-extension#70]
Tested with at least 30 latin american cities and not are reconoced for the plugin

Tested: 
Peru= 3 cities
Chile= every main capital city
Argentina, Bolivia, Brazil, etc.

All send the message "invalid city"

**Comment by PikaDude** [comment]
The plan is to allow users to search for locations via name rather than zip/post codes in a future update.

**Comment by PikaDude** [comment]
Moved to #79 with some improvements made in #71 and 2862456457f9c67b2c12e6f12cf243a6beddad24
