### ISSUE TITLE
Add ? note support to town tune

### ISSUE THREAD

**Issue by PikaDude** [animal-crossing-music-extension/ac-music-extension#75]
In the AC games, there's support for a ? note, which is just a randomly selected note. This allows the note to variate each time the town tune plays.

**Comment by PikaDude** [comment]
Was this solved?

**Comment by Julian-MM** [comment]
Yes, though not yet committed

**Comment by PikaDude** [comment]
Okay, cool. For next time though, don't close issues first. Push the feature/fix branch with the new changes first, then create a PR saying that "this closes issue #x", and the issue will automatically be closed when the PR is approved and merged.

**Comment by Julian-MM** [comment]
Thanks for the heads-up, I'll do that
