### ISSUE TITLE
[request] Use opus over vorbis for audio encoding

### ISSUE THREAD

**Issue by borring** [animal-crossing-music-extension/ac-music-extension#9]
I chose a random audio file from the google drive folder:

```
new-leaf-raining/10am.ogg
```

and re-encoded it using ffmpeg:

```
ffmpeg -i 10am.ogg -acodec opus -vn -f ogg out.ogg
```

and found that the filesize was reduced by 67%. Either the original files were
encoded with excessively high bitrates or opus is just that much better. I
didn't hear any difference in quality either.

**Comment by JdotCarver** [comment]
Yep, that's a great idea! 
I'm not savvy enough to know how audio compression and optimization goes but recently people have suggested lowering the bit rate too. I like my 320kb/s but I guess since it's background music it won't hurt much. (Or if your encode lowers bit rate too I don't really know.) And if I combine that with your idea of re-encoding the whole library I'm sure we'll make stark progress on the size issue. Great suggestion Mr.

**Comment by borring** [comment]
I downloaded the library from the Google Drive link, thinking to re-encode the files. But I realized that some of the audio files are already quite small (and of quite poor quality). Of note is the music in `new-leaf-snowing`. The filesizes are pretty small, and the audio quality is much lower than `new-leaf-raining` for example.

Will you be able to find higher quality sources for `new-leaf-snowing`?

**Comment by JdotCarver** [comment]
That's because they're the original extension's version ;)

**Comment by TheDirtySpaceman** [comment]
I have noticed on many the original Animal Forest/Crossing track there is an extremely noticeable crackle. The quality of the entire music library should probably be revisited. This isn't too difficult of a task either there are many very clean rips of the music on the animal crossing reddit in FLAC format. This could be converted to oog in the most appropriate compression. This could be done by a non-programmer even.

**Comment by JdotCarver** [comment]
Great, I didn't know the AC Reddit had FLAC files to download, <s> though I haven't noticed any crackling </s>, but I guess if its only me it wouldn't hurt if I updated the files.
The crackling is very possible, these are low quality files that need updating.

**Comment by PikaDude** [comment]
Opus actually increases the file size in comparison to Vorbis. The FFMPEG command used has a default bitrate that is substantially lower than the original, hence why the file size ended up smaller. I'm currently in the process of converting songs and finding replacements without crackle here PikaDude/ac-music-extension-revived#1 The New Leaf songs with crackles have been replaced with dumps from my own cartridge and no longer contain a crackle.
