### ISSUE TITLE
Playing 2 am music when it most certainly isn't 2 am

### ISSUE THREAD

**Issue by Piefactor** [animal-crossing-music-extension/ac-music-extension#93]
Turning on and off or toggling other settings doesn't fix it.  [Screenshot](https://imgur.com/a/omRxZ8c)

**Comment by Julian-MM** [comment]
Have you tried restarting Chrome?

**Comment by Piefactor** [comment]
That seems to have worked.  It's the simple things sometimes.

**Comment by Julian-MM** [comment]
It's not a permanent fix, but the bug that causes this will be fixed in the next update ^^
