### ISSUE TITLE
Animal Forest/Animal Crossing Rain setting plays the Snow version

### ISSUE THREAD

**Issue by mscholes** [animal-crossing-music-extension/ac-music-extension#94]
Tested for 8am, 9am, 10am, and 11am. Using both live weather (which is currently raining) and the Raining option, it plays and displays the Snowing version of the song. This is not the case for Wild World/City Folk/Let's Go to the City and New Leaf, which play the Raining version correctly.

Screenshots:
https://imgur.com/a/2L4WV4f

**Comment by PikaDude** [comment]
This is because Animal Crossing doesn't have hourly raining music. It has a single 1 minute loop that would play for as long as it rains. It is planned to implement it for those who really want it, but for now we've kept it like this.

**Comment by Julian-MM** [comment]
Should we close this issue then?

**Comment by mscholes** [comment]
Sounds great! Look forward to the added feature if it makes the cut.
